build:
    environment:
        php:
            version: 7.1

before_commands:
    - "composer install --no-dev"

tools:
    external_code_coverage:
        timeout: 1200
    php_code_coverage:
        enabled: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["src/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["example", "example-phpunit", "patches", "tests", 'vendor']
    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            paths: ["src/*"]
    php_loc:
        enabled: true
        excluded_dirs: ["example", "example-phpunit", "patches", "tests", 'vendor']
    php_pdepend:
        enabled: true
        excluded_dirs: ["example", "example-phpunit", "patches", "tests", 'vendor']
    php_analyzer:
        enabled: true
        filter:
            paths: ["src/*"]
    sensiolabs_security_checker: true
